GET http://localhost:3000/api/categories


###
GET http://localhost:3000/api/categories/20


###
POST http://localhost:3000/api/item

###
GET http://localhost:3000/api/itemCategory?category=Drinks

###
GET http://localhost:3000/api/itemCategory


###

GET http://localhost:3000/api/wispay/credit?rfid=2558453492

###

POST http://localhost:3000/api/wispay/credit

###

GET http://localhost:3000/api/wispay/user